name: clsw
favicon: null
layout_spectrum: 0.6871581168379635
typography_spectrum: 0.3997402109671384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.4020380659494549
  lightness: 0.5903591336682439
  saturation: 0.07223960314877331
  rhythmicContrast: 0.561411845497787
purpose: []
